### ISSUE TITLE
Add other torrentProject domains on permitted URLs

### ISSUE THREAD

**Issue by fracarma** [N-Upchurch/torrentProject2MagnetFixer#1]
First, thank you for this extension! It spares a few clicks every time I stumble upon this website :)

Apart from `torrentproject2.com` permission 

<img width="501" alt="image" src="https://github.com/N-Upchurch/torrentProject2MagnetFixer/assets/12348998/5363c728-62b7-4113-afe3-964a76844409">

this extension should add:

* torrentproject.cc

**Comment by N-Upchurch** [comment]
Thanks! Fixed with https://github.com/N-Upchurch/torrentProject2MagnetFixer/pull/3.
